In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6])

In [4]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a.ndim # Dimension

1

In [8]:
a.shape # gives the shape of the array.

(6,)

In [15]:
np.linspace(0,20,14) # Gives equal spaces of 14 between 0 and 20 as given.

array([ 0.        ,  1.53846154,  3.07692308,  4.61538462,  6.15384615,
        7.69230769,  9.23076923, 10.76923077, 12.30769231, 13.84615385,
       15.38461538, 16.92307692, 18.46153846, 20.        ])

In [17]:
type(a) # Gives the type of array.

numpy.ndarray

In [21]:
A = np.arange(12).reshape(4,3)

In [22]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# Perform addition of elements from top to bottom(axis = 0).

In [24]:
np.sum(A,axis = 0)

array([18, 22, 26])

# Perform addition of elements from left to right (axis = 1).

In [26]:
np.sum(A , axis = 1)

array([ 3, 12, 21, 30])

# Fitbit Data analysis.

In [61]:
data = np.loadtxt(r"C:\Users\DELL\Desktop\Scaler Numpy and Pandas\fitness.txt" , dtype = "str")

In [62]:
data

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '100', '6', '8', '0', '65'],
       ['23-10-2017', '3158', '200', '99', '5', '0', '65'],
       ['24-10-2017', '4383', '200', '143', '4', '0', '64'],
       ['25-10-2017', '3881', '200', '125', '5', '0', '64'],
       ['26-10-2017', '4037', '200', '129', '6', '0', '64'],
       ['27-10-2017', '202', '200', '6', '8', '0', '64'],
       ['28-10-2017', '292', '200', '9', '5', '0', '64'],
       ['29-10-2017', '330', '300', '10', '6', '0', '64'],
       ['30-10-2017', '2209', '200', '72', '5', '0', '64'],
       ['31-10-2017', '4550', '300', '150', '8', '500', '64'],
       ['01-11-2017', '4435', '300', '141', '5', '0', '64'],
       ['02-11-2017', '4779', '300', '156', '4', '0', '64'],
       ['03-11-2017', '1831', '300', '57', '5', '0', '64'],
       ['04-11-2017', '2255', '300', '72', '4', '0', '64'],
       ['05-11-2017', '539', '300', '17', '5', '500', '64'],
       ['06-11-2017', '5464', '300', '181', '4', '0', '64'],
       ['07-11-2017', '6041', '200', '197', '3', '0', '64'],
       ['08-11-2017', '4068', '300', '131', '2', '0', '64'],
       ['09-11-2017', '4683', '300', '154', '9', '0', '64'],
       ['10-11-2017', '4033', '300', '137', '5', '0', '64'],
       ['11-11-2017', '6314', '300', '193', '6', '500', '64'],
       ['12-11-2017', '614', '300', '19', '4', '500', '64'],
       ['13-11-2017', '3149', '300', '101', '5', '500', '64'],
       ['14-11-2017', '4005', '300', '139', '8', '500', '64'],
       ['15-11-2017', '4880', '300', '164', '4', '500', '64'],
       ['16-11-2017', '4136', '300', '137', '5', '500', '64'],
       ['17-11-2017', '705', '300', '22', '6', '500', '64'],
       ['18-11-2017', '570', '200', '17', '5', '500', '64'],
       ['19-11-2017', '269', '300', '9', '6', '500', '64'],
       ['20-11-2017', '4275', '300', '145', '5', '0', '64'],
       ['21-11-2017', '5999', '300', '192', '6', '0', '64'],
       ['22-11-2017', '4421', '300', '146', '5', '0', '64'],
       ['23-11-2017', '6930', '300', '234', '6', '0', '64'],
       ['24-11-2017', '5195', '300', '167', '5', '0', '64'],
       ['25-11-2017', '546', '300', '16', '6', '0', '64'],
       ['26-11-2017', '493', '300', '17', '7', '500', '64'],
       ['27-11-2017', '995', '300', '32', '6', '500', '64'],
       ['28-11-2017', '1163', '200', '35', '7', '500', '64'],
       ['29-11-2017', '6676', '100', '220', '6', '500', '64'],
       ['30-11-2017', '3608', '300', '116', '5', '500', '64'],
       ['01-12-2017', '774', '300', '23', '6', '500', '64'],
       ['02-12-2017', '1421', '300', '44', '7', '500', '64'],
       ['03-12-2017', '4064', '300', '131', '8', '500', '64'],
       ['04-12-2017', '2725', '300', '86', '8', '500', '64'],
       ['05-12-2017', '5934', '300', '194', '7', '500', '64'],
       ['06-12-2017', '1867', '300', '60', '8', '500', '64'],
       ['07-12-2017', '3721', '100', '121', '5', '500', '64'],
       ['08-12-2017', '2374', '200', '76', '4', '0', '64'],
       ['09-12-2017', '2909', '200', '93', '3', '500', '64'],
       ['10-12-2017', '1648', '100', '53', '3', '500', '64'],
       ['11-12-2017', '799', '100', '25', '4', '0', '64'],
       ['12-12-2017', '7102', '200', '227', '5', '500', '64'],
       ['13-12-2017', '3941', '200', '125', '5', '500', '64'],
       ['14-12-2017', '7422', '300', '243', '5', '500', '64'],
       ['15-12-2017', '437', '200', '14', '3', '500', '64'],
       ['16-12-2017', '1231', '200', '39', '4', '500', '64'],
       ['17-12-2017', '1696', '100', '55', '4', '0', '64'],
       ['18-12-2017', '4921', '200', '158', '5', '500', '64'],
       ['19-12-2017', '221', '100', '7', '5', '500', '64'],
       ['20-12-2017', '6500', '200', '213', '5', '500', '64'],
       ['21-12-2017', '3575', '200', '116', '5', '500', '64'],
       ['22-12-2017', '4061', '100', '129', '5', '0', '64'],
       ['23-12-2017', '651', '100', '21', '5', '0', '64'],
       ['24-12-2017', '753', '100', '28', '4', '0', '64'],
       ['25-12-2017', '518', '100', '16', '3', '0', '64'],
       ['26-12-2017', '5537', '300', '180', '4', '500', '64'],
       ['27-12-2017', '4108', '200', '138', '5', '500', '64'],
       ['28-12-2017', '5376', '300', '176', '5', '500', '64'],
       ['29-12-2017', '3066', '200', '99', '4', '500', '64'],
       ['30-12-2017', '177', '100', '5', '5', '0', '64'],
       ['31-12-2017', '36', '100', '1', '3', '0', '64'],
       ['01-01-2018', '299', '100', '10', '3', '0', '64'],
       ['02-01-2018', '1447', '200', '47', '3', '0', '64'],
       ['03-01-2018', '2599', '200', '84', '2', '0', '64'],
       ['04-01-2018', '702', '100', '23', '3', '0', '64'],
       ['05-01-2018', '133', '100', '4', '2', '0', '64'],
       ['06-01-2018', '153', '300', '0', '8', '0', '64'],
       ['07-01-2018', '500', '200', '0', '5', '500', '64'],
       ['08-01-2018', '2127', '200', '0', '5', '0', '64'],
       ['09-01-2018', '2203', '300', '0', '5', '500', '64']], dtype='<U10')

In [63]:
type(data)

numpy.ndarray

In [64]:
data.shape

(96, 7)

In [65]:
data.ndim

2

In [66]:
# print the first 5 rows ofd the data.

In [67]:
data

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '100', '6', '8', '0', '65'],
       ['23-10-2017', '3158', '200', '99', '5', '0', '65'],
       ['24-10-2017', '4383', '200', '143', '4', '0', '64'],
       ['25-10-2017', '3881', '200', '125', '5', '0', '64'],
       ['26-10-2017', '4037', '200', '129', '6', '0', '64'],
       ['27-10-2017', '202', '200', '6', '8', '0', '64'],
       ['28-10-2017', '292', '200', '9', '5', '0', '64'],
       ['29-10-2017', '330', '300', '10', '6', '0', '64'],
       ['30-10-2017', '2209', '200', '72', '5', '0', '64'],
       ['31-10-2017', '4550', '300', '150', '8', '500', '64'],
       ['01-11-2017', '4435', '300', '141', '5', '0', '64'],
       ['02-11-2017', '4779', '300', '156', '4', '0', '64'],
       ['03-11-2017', '1831', '300', '57', '5', '0', '64'],
       ['04-11-2017', '2255', '300', '72', '4', '0', '64'],
       ['05-11-2017', '539', '300', '17', '5', '500', '64'],
       ['06-11-2017', '5464', '300', '181', '4', '0', '64'],
       ['07-11-2017', '6041', '200', '197', '3', '0', '64'],
       ['08-11-2017', '4068', '300', '131', '2', '0', '64'],
       ['09-11-2017', '4683', '300', '154', '9', '0', '64'],
       ['10-11-2017', '4033', '300', '137', '5', '0', '64'],
       ['11-11-2017', '6314', '300', '193', '6', '500', '64'],
       ['12-11-2017', '614', '300', '19', '4', '500', '64'],
       ['13-11-2017', '3149', '300', '101', '5', '500', '64'],
       ['14-11-2017', '4005', '300', '139', '8', '500', '64'],
       ['15-11-2017', '4880', '300', '164', '4', '500', '64'],
       ['16-11-2017', '4136', '300', '137', '5', '500', '64'],
       ['17-11-2017', '705', '300', '22', '6', '500', '64'],
       ['18-11-2017', '570', '200', '17', '5', '500', '64'],
       ['19-11-2017', '269', '300', '9', '6', '500', '64'],
       ['20-11-2017', '4275', '300', '145', '5', '0', '64'],
       ['21-11-2017', '5999', '300', '192', '6', '0', '64'],
       ['22-11-2017', '4421', '300', '146', '5', '0', '64'],
       ['23-11-2017', '6930', '300', '234', '6', '0', '64'],
       ['24-11-2017', '5195', '300', '167', '5', '0', '64'],
       ['25-11-2017', '546', '300', '16', '6', '0', '64'],
       ['26-11-2017', '493', '300', '17', '7', '500', '64'],
       ['27-11-2017', '995', '300', '32', '6', '500', '64'],
       ['28-11-2017', '1163', '200', '35', '7', '500', '64'],
       ['29-11-2017', '6676', '100', '220', '6', '500', '64'],
       ['30-11-2017', '3608', '300', '116', '5', '500', '64'],
       ['01-12-2017', '774', '300', '23', '6', '500', '64'],
       ['02-12-2017', '1421', '300', '44', '7', '500', '64'],
       ['03-12-2017', '4064', '300', '131', '8', '500', '64'],
       ['04-12-2017', '2725', '300', '86', '8', '500', '64'],
       ['05-12-2017', '5934', '300', '194', '7', '500', '64'],
       ['06-12-2017', '1867', '300', '60', '8', '500', '64'],
       ['07-12-2017', '3721', '100', '121', '5', '500', '64'],
       ['08-12-2017', '2374', '200', '76', '4', '0', '64'],
       ['09-12-2017', '2909', '200', '93', '3', '500', '64'],
       ['10-12-2017', '1648', '100', '53', '3', '500', '64'],
       ['11-12-2017', '799', '100', '25', '4', '0', '64'],
       ['12-12-2017', '7102', '200', '227', '5', '500', '64'],
       ['13-12-2017', '3941', '200', '125', '5', '500', '64'],
       ['14-12-2017', '7422', '300', '243', '5', '500', '64'],
       ['15-12-2017', '437', '200', '14', '3', '500', '64'],
       ['16-12-2017', '1231', '200', '39', '4', '500', '64'],
       ['17-12-2017', '1696', '100', '55', '4', '0', '64'],
       ['18-12-2017', '4921', '200', '158', '5', '500', '64'],
       ['19-12-2017', '221', '100', '7', '5', '500', '64'],
       ['20-12-2017', '6500', '200', '213', '5', '500', '64'],
       ['21-12-2017', '3575', '200', '116', '5', '500', '64'],
       ['22-12-2017', '4061', '100', '129', '5', '0', '64'],
       ['23-12-2017', '651', '100', '21', '5', '0', '64'],
       ['24-12-2017', '753', '100', '28', '4', '0', '64'],
       ['25-12-2017', '518', '100', '16', '3', '0', '64'],
       ['26-12-2017', '5537', '300', '180', '4', '500', '64'],
       ['27-12-2017', '4108', '200', '138', '5', '500', '64'],
       ['28-12-2017', '5376', '300', '176', '5', '500', '64'],
       ['29-12-2017', '3066', '200', '99', '4', '500', '64'],
       ['30-12-2017', '177', '100', '5', '5', '0', '64'],
       ['31-12-2017', '36', '100', '1', '3', '0', '64'],
       ['01-01-2018', '299', '100', '10', '3', '0', '64'],
       ['02-01-2018', '1447', '200', '47', '3', '0', '64'],
       ['03-01-2018', '2599', '200', '84', '2', '0', '64'],
       ['04-01-2018', '702', '100', '23', '3', '0', '64'],
       ['05-01-2018', '133', '100', '4', '2', '0', '64'],
       ['06-01-2018', '153', '300', '0', '8', '0', '64'],
       ['07-01-2018', '500', '200', '0', '5', '500', '64'],
       ['08-01-2018', '2127', '200', '0', '5', '0', '64'],
       ['09-01-2018', '2203', '300', '0', '5', '500', '64']], dtype='<U10')

In [68]:
data[:5,:]

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66']],
      dtype='<U10')

# Extract the first row of the data.

In [69]:
data[0]

array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

# What are the number of records and number of features in the data.

In [70]:
data.shape

(96, 7)

In [71]:
# so there are 96 records and 7 features in the data.

# Extract the first column of the data.

In [72]:
data[: , :1]

array([['06-10-2017'],
       ['07-10-2017'],
       ['08-10-2017'],
       ['09-10-2017'],
       ['10-10-2017'],
       ['11-10-2017'],
       ['12-10-2017'],
       ['13-10-2017'],
       ['14-10-2017'],
       ['15-10-2017'],
       ['16-10-2017'],
       ['17-10-2017'],
       ['18-10-2017'],
       ['19-10-2017'],
       ['20-10-2017'],
       ['21-10-2017'],
       ['22-10-2017'],
       ['23-10-2017'],
       ['24-10-2017'],
       ['25-10-2017'],
       ['26-10-2017'],
       ['27-10-2017'],
       ['28-10-2017'],
       ['29-10-2017'],
       ['30-10-2017'],
       ['31-10-2017'],
       ['01-11-2017'],
       ['02-11-2017'],
       ['03-11-2017'],
       ['04-11-2017'],
       ['05-11-2017'],
       ['06-11-2017'],
       ['07-11-2017'],
       ['08-11-2017'],
       ['09-11-2017'],
       ['10-11-2017'],
       ['11-11-2017'],
       ['12-11-2017'],
       ['13-11-2017'],
       ['14-11-2017'],
       ['15-11-2017'],
       ['16-11-2017'],
       ['17-11-2017'],
       ['18-11-2017'],
       ['19-11-2017'],
       ['20-11-2017'],
       ['21-11-2017'],
       ['22-11-2017'],
       ['23-11-2017'],
       ['24-11-2017'],
       ['25-11-2017'],
       ['26-11-2017'],
       ['27-11-2017'],
       ['28-11-2017'],
       ['29-11-2017'],
       ['30-11-2017'],
       ['01-12-2017'],
       ['02-12-2017'],
       ['03-12-2017'],
       ['04-12-2017'],
       ['05-12-2017'],
       ['06-12-2017'],
       ['07-12-2017'],
       ['08-12-2017'],
       ['09-12-2017'],
       ['10-12-2017'],
       ['11-12-2017'],
       ['12-12-2017'],
       ['13-12-2017'],
       ['14-12-2017'],
       ['15-12-2017'],
       ['16-12-2017'],
       ['17-12-2017'],
       ['18-12-2017'],
       ['19-12-2017'],
       ['20-12-2017'],
       ['21-12-2017'],
       ['22-12-2017'],
       ['23-12-2017'],
       ['24-12-2017'],
       ['25-12-2017'],
       ['26-12-2017'],
       ['27-12-2017'],
       ['28-12-2017'],
       ['29-12-2017'],
       ['30-12-2017'],
       ['31-12-2017'],
       ['01-01-2018'],
       ['02-01-2018'],
       ['03-01-2018'],
       ['04-01-2018'],
       ['05-01-2018'],
       ['06-01-2018'],
       ['07-01-2018'],
       ['08-01-2018'],
       ['09-01-2018']], dtype='<U10')

In [73]:
data[:,0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12-2017',
       '09-12-2017', '10-12-2017', '11-12-2017', '12-12-2017',
       '13-12-2017', '14-12-2017', '15-12-2017', '16-12-2017',
       '17-12-2017', '18-12-2017', '19-12-2017', '20-12-2017',
       '21-12-2017', '22-12-2017', '23-12-2017', '24-12-2017',
       '25-12-2017', '26-12-2017', '27-12-2017', '28-12-2017',
       '29-12-2017', '30-12-2017', '31-12-2017', '01-01-2018',
       '02-01-2018', '03-01-2018', '04-01-2018', '05-01-2018',
       '06-01-2018', '07-01-2018', '08-01-2018', '09-01-2018'],
      dtype='<U10')

In [74]:
data.T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12-2017',
       '09-12-2017', '10-12-2017', '11-12-2017', '12-12-2017',
       '13-12-2017', '14-12-2017', '15-12-2017', '16-12-2017',
       '17-12-2017', '18-12-2017', '19-12-2017', '20-12-2017',
       '21-12-2017', '22-12-2017', '23-12-2017', '24-12-2017',
       '25-12-2017', '26-12-2017', '27-12-2017', '28-12-2017',
       '29-12-2017', '30-12-2017', '31-12-2017', '01-01-2018',
       '02-01-2018', '03-01-2018', '04-01-2018', '05-01-2018',
       '06-01-2018', '07-01-2018', '08-01-2018', '09-01-2018'],
      dtype='<U10')

# Extract the first two columns of the data.

In [75]:
data[: , :2]

array([['06-10-2017', '5464'],
       ['07-10-2017', '6041'],
       ['08-10-2017', '25'],
       ['09-10-2017', '5461'],
       ['10-10-2017', '6915'],
       ['11-10-2017', '4545'],
       ['12-10-2017', '4340'],
       ['13-10-2017', '1230'],
       ['14-10-2017', '61'],
       ['15-10-2017', '1258'],
       ['16-10-2017', '3148'],
       ['17-10-2017', '4687'],
       ['18-10-2017', '4732'],
       ['19-10-2017', '3519'],
       ['20-10-2017', '1580'],
       ['21-10-2017', '2822'],
       ['22-10-2017', '181'],
       ['23-10-2017', '3158'],
       ['24-10-2017', '4383'],
       ['25-10-2017', '3881'],
       ['26-10-2017', '4037'],
       ['27-10-2017', '202'],
       ['28-10-2017', '292'],
       ['29-10-2017', '330'],
       ['30-10-2017', '2209'],
       ['31-10-2017', '4550'],
       ['01-11-2017', '4435'],
       ['02-11-2017', '4779'],
       ['03-11-2017', '1831'],
       ['04-11-2017', '2255'],
       ['05-11-2017', '539'],
       ['06-11-2017', '5464'],
       ['07-11-2017', '6041'],
       ['08-11-2017', '4068'],
       ['09-11-2017', '4683'],
       ['10-11-2017', '4033'],
       ['11-11-2017', '6314'],
       ['12-11-2017', '614'],
       ['13-11-2017', '3149'],
       ['14-11-2017', '4005'],
       ['15-11-2017', '4880'],
       ['16-11-2017', '4136'],
       ['17-11-2017', '705'],
       ['18-11-2017', '570'],
       ['19-11-2017', '269'],
       ['20-11-2017', '4275'],
       ['21-11-2017', '5999'],
       ['22-11-2017', '4421'],
       ['23-11-2017', '6930'],
       ['24-11-2017', '5195'],
       ['25-11-2017', '546'],
       ['26-11-2017', '493'],
       ['27-11-2017', '995'],
       ['28-11-2017', '1163'],
       ['29-11-2017', '6676'],
       ['30-11-2017', '3608'],
       ['01-12-2017', '774'],
       ['02-12-2017', '1421'],
       ['03-12-2017', '4064'],
       ['04-12-2017', '2725'],
       ['05-12-2017', '5934'],
       ['06-12-2017', '1867'],
       ['07-12-2017', '3721'],
       ['08-12-2017', '2374'],
       ['09-12-2017', '2909'],
       ['10-12-2017', '1648'],
       ['11-12-2017', '799'],
       ['12-12-2017', '7102'],
       ['13-12-2017', '3941'],
       ['14-12-2017', '7422'],
       ['15-12-2017', '437'],
       ['16-12-2017', '1231'],
       ['17-12-2017', '1696'],
       ['18-12-2017', '4921'],
       ['19-12-2017', '221'],
       ['20-12-2017', '6500'],
       ['21-12-2017', '3575'],
       ['22-12-2017', '4061'],
       ['23-12-2017', '651'],
       ['24-12-2017', '753'],
       ['25-12-2017', '518'],
       ['26-12-2017', '5537'],
       ['27-12-2017', '4108'],
       ['28-12-2017', '5376'],
       ['29-12-2017', '3066'],
       ['30-12-2017', '177'],
       ['31-12-2017', '36'],
       ['01-01-2018', '299'],
       ['02-01-2018', '1447'],
       ['03-01-2018', '2599'],
       ['04-01-2018', '702'],
       ['05-01-2018', '133'],
       ['06-01-2018', '153'],
       ['07-01-2018', '500'],
       ['08-01-2018', '2127'],
       ['09-01-2018', '2203']], dtype='<U10')

In [76]:
data.T[:2]

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-12-2017', '08-12-2017',
        '09-12-2017', '10-12-2017', '11-12-2017', '12-12-2017',
        '13-12-2017', '14-12-2017', '15-12-2017', '16-12-2017',
        '17-12-2017', '18-12-2017', '19-12-2017', '20-12-2017',
        '21-12-2017', '22-12-2017', '23-12-2017', '24-12-2017',
        '25-12-2017', '26-12-2017', '27-12-2017', '28-12-2017',
        '29-12-2017', '30-12-2017', '31-12-2017', '01-01-2018',
        '02-01-2018', '03-01-2018', '04-01-2018', '05-01-2018',
        '06-01-2018', '07-01-2018', '08-01-2018', '09-01-2018'],
       ['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230',
        '61', '1258', '3148', '4687', '4732', '3519', '1580', '2822',
        '181', '3158', '4383', '3881', '4037', '202', '292', '330',
        '2209', '4550', '4435', '4779', '1831', '2255', '539', '5464',
        '6041', '4068', '4683', '4033', '6314', '614', '3149', '4005',
        '4880', '4136', '705', '570', '269', '4275', '5999', '4421',
        '6930', '5195', '546', '493', '995', '1163', '6676', '3608',
        '774', '1421', '4064', '2725', '5934', '1867', '3721', '2374',
        '2909', '1648', '799', '7102', '3941', '7422', '437', '1231',
        '1696', '4921', '221', '6500', '3575', '4061', '651', '753',
        '518', '5537', '4108', '5376', '3066', '177', '36', '299',
        '1447', '2599', '702', '133', '153', '500', '2127', '2203']],
      dtype='<U10')

In [77]:
data.T[:2]

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-12-2017', '08-12-2017',
        '09-12-2017', '10-12-2017', '11-12-2017', '12-12-2017',
        '13-12-2017', '14-12-2017', '15-12-2017', '16-12-2017',
        '17-12-2017', '18-12-2017', '19-12-2017', '20-12-2017',
        '21-12-2017', '22-12-2017', '23-12-2017', '24-12-2017',
        '25-12-2017', '26-12-2017', '27-12-2017', '28-12-2017',
        '29-12-2017', '30-12-2017', '31-12-2017', '01-01-2018',
        '02-01-2018', '03-01-2018', '04-01-2018', '05-01-2018',
        '06-01-2018', '07-01-2018', '08-01-2018', '09-01-2018'],
       ['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230',
        '61', '1258', '3148', '4687', '4732', '3519', '1580', '2822',
        '181', '3158', '4383', '3881', '4037', '202', '292', '330',
        '2209', '4550', '4435', '4779', '1831', '2255', '539', '5464',
        '6041', '4068', '4683', '4033', '6314', '614', '3149', '4005',
        '4880', '4136', '705', '570', '269', '4275', '5999', '4421',
        '6930', '5195', '546', '493', '995', '1163', '6676', '3608',
        '774', '1421', '4064', '2725', '5934', '1867', '3721', '2374',
        '2909', '1648', '799', '7102', '3941', '7422', '437', '1231',
        '1696', '4921', '221', '6500', '3575', '4061', '651', '753',
        '518', '5537', '4108', '5376', '3066', '177', '36', '299',
        '1447', '2599', '702', '133', '153', '500', '2127', '2203']],
      dtype='<U10')

In [79]:
data.T[:2]

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-12-2017', '08-12-2017',
        '09-12-2017', '10-12-2017', '11-12-2017', '12-12-2017',
        '13-12-2017', '14-12-2017', '15-12-2017', '16-12-2017',
        '17-12-2017', '18-12-2017', '19-12-2017', '20-12-2017',
        '21-12-2017', '22-12-2017', '23-12-2017', '24-12-2017',
        '25-12-2017', '26-12-2017', '27-12-2017', '28-12-2017',
        '29-12-2017', '30-12-2017', '31-12-2017', '01-01-2018',
        '02-01-2018', '03-01-2018', '04-01-2018', '05-01-2018',
        '06-01-2018', '07-01-2018', '08-01-2018', '09-01-2018'],
       ['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230',
        '61', '1258', '3148', '4687', '4732', '3519', '1580', '2822',
        '181', '3158', '4383', '3881', '4037', '202', '292', '330',
        '2209', '4550', '4435', '4779', '1831', '2255', '539', '5464',
        '6041', '4068', '4683', '4033', '6314', '614', '3149', '4005',
        '4880', '4136', '705', '570', '269', '4275', '5999', '4421',
        '6930', '5195', '546', '493', '995', '1163', '6676', '3608',
        '774', '1421', '4064', '2725', '5934', '1867', '3721', '2374',
        '2909', '1648', '799', '7102', '3941', '7422', '437', '1231',
        '1696', '4921', '221', '6500', '3575', '4061', '651', '753',
        '518', '5537', '4108', '5376', '3066', '177', '36', '299',
        '1447', '2599', '702', '133', '153', '500', '2127', '2203']],
      dtype='<U10')

In [80]:
date , step_count = data.T[:2]

In [81]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12-2017',
       '09-12-2017', '10-12-2017', '11-12-2017', '12-12-2017',
       '13-12-2017', '14-12-2017', '15-12-2017', '16-12-2017',
       '17-12-2017', '18-12-2017', '19-12-2017', '20-12-2017',
       '21-12-2017', '22-12-2017', '23-12-2017', '24-12-2017',
       '25-12-2017', '26-12-2017', '27-12-2017', '28-12-2017',
       '29-12-2017', '30-12-2017', '31-12-2017', '01-01-2018',
       '02-01-2018', '03-01-2018', '04-01-2018', '05-01-2018',
       '06-01-2018', '07-01-2018', '08-01-2018', '09-01-2018'],
      dtype='<U10')

In [82]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [83]:
data

array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '100', '6', '8', '0', '65'],
       ['23-10-2017', '3158', '200', '99', '5', '0', '65'],
       ['24-10-2017', '4383', '200', '143', '4', '0', '64'],
       ['25-10-2017', '3881', '200', '125', '5', '0', '64'],
       ['26-10-2017', '4037', '200', '129', '6', '0', '64'],
       ['27-10-2017', '202', '200', '6', '8', '0', '64'],
       ['28-10-2017', '292', '200', '9', '5', '0', '64'],
       ['29-10-2017', '330', '300', '10', '6', '0', '64'],
       ['30-10-2017', '2209', '200', '72', '5', '0', '64'],
       ['31-10-2017', '4550', '300', '150', '8', '500', '64'],
       ['01-11-2017', '4435', '300', '141', '5', '0', '64'],
       ['02-11-2017', '4779', '300', '156', '4', '0', '64'],
       ['03-11-2017', '1831', '300', '57', '5', '0', '64'],
       ['04-11-2017', '2255', '300', '72', '4', '0', '64'],
       ['05-11-2017', '539', '300', '17', '5', '500', '64'],
       ['06-11-2017', '5464', '300', '181', '4', '0', '64'],
       ['07-11-2017', '6041', '200', '197', '3', '0', '64'],
       ['08-11-2017', '4068', '300', '131', '2', '0', '64'],
       ['09-11-2017', '4683', '300', '154', '9', '0', '64'],
       ['10-11-2017', '4033', '300', '137', '5', '0', '64'],
       ['11-11-2017', '6314', '300', '193', '6', '500', '64'],
       ['12-11-2017', '614', '300', '19', '4', '500', '64'],
       ['13-11-2017', '3149', '300', '101', '5', '500', '64'],
       ['14-11-2017', '4005', '300', '139', '8', '500', '64'],
       ['15-11-2017', '4880', '300', '164', '4', '500', '64'],
       ['16-11-2017', '4136', '300', '137', '5', '500', '64'],
       ['17-11-2017', '705', '300', '22', '6', '500', '64'],
       ['18-11-2017', '570', '200', '17', '5', '500', '64'],
       ['19-11-2017', '269', '300', '9', '6', '500', '64'],
       ['20-11-2017', '4275', '300', '145', '5', '0', '64'],
       ['21-11-2017', '5999', '300', '192', '6', '0', '64'],
       ['22-11-2017', '4421', '300', '146', '5', '0', '64'],
       ['23-11-2017', '6930', '300', '234', '6', '0', '64'],
       ['24-11-2017', '5195', '300', '167', '5', '0', '64'],
       ['25-11-2017', '546', '300', '16', '6', '0', '64'],
       ['26-11-2017', '493', '300', '17', '7', '500', '64'],
       ['27-11-2017', '995', '300', '32', '6', '500', '64'],
       ['28-11-2017', '1163', '200', '35', '7', '500', '64'],
       ['29-11-2017', '6676', '100', '220', '6', '500', '64'],
       ['30-11-2017', '3608', '300', '116', '5', '500', '64'],
       ['01-12-2017', '774', '300', '23', '6', '500', '64'],
       ['02-12-2017', '1421', '300', '44', '7', '500', '64'],
       ['03-12-2017', '4064', '300', '131', '8', '500', '64'],
       ['04-12-2017', '2725', '300', '86', '8', '500', '64'],
       ['05-12-2017', '5934', '300', '194', '7', '500', '64'],
       ['06-12-2017', '1867', '300', '60', '8', '500', '64'],
       ['07-12-2017', '3721', '100', '121', '5', '500', '64'],
       ['08-12-2017', '2374', '200', '76', '4', '0', '64'],
       ['09-12-2017', '2909', '200', '93', '3', '500', '64'],
       ['10-12-2017', '1648', '100', '53', '3', '500', '64'],
       ['11-12-2017', '799', '100', '25', '4', '0', '64'],
       ['12-12-2017', '7102', '200', '227', '5', '500', '64'],
       ['13-12-2017', '3941', '200', '125', '5', '500', '64'],
       ['14-12-2017', '7422', '300', '243', '5', '500', '64'],
       ['15-12-2017', '437', '200', '14', '3', '500', '64'],
       ['16-12-2017', '1231', '200', '39', '4', '500', '64'],
       ['17-12-2017', '1696', '100', '55', '4', '0', '64'],
       ['18-12-2017', '4921', '200', '158', '5', '500', '64'],
       ['19-12-2017', '221', '100', '7', '5', '500', '64'],
       ['20-12-2017', '6500', '200', '213', '5', '500', '64'],
       ['21-12-2017', '3575', '200', '116', '5', '500', '64'],
       ['22-12-2017', '4061', '100', '129', '5', '0', '64'],
       ['23-12-2017', '651', '100', '21', '5', '0', '64'],
       ['24-12-2017', '753', '100', '28', '4', '0', '64'],
       ['25-12-2017', '518', '100', '16', '3', '0', '64'],
       ['26-12-2017', '5537', '300', '180', '4', '500', '64'],
       ['27-12-2017', '4108', '200', '138', '5', '500', '64'],
       ['28-12-2017', '5376', '300', '176', '5', '500', '64'],
       ['29-12-2017', '3066', '200', '99', '4', '500', '64'],
       ['30-12-2017', '177', '100', '5', '5', '0', '64'],
       ['31-12-2017', '36', '100', '1', '3', '0', '64'],
       ['01-01-2018', '299', '100', '10', '3', '0', '64'],
       ['02-01-2018', '1447', '200', '47', '3', '0', '64'],
       ['03-01-2018', '2599', '200', '84', '2', '0', '64'],
       ['04-01-2018', '702', '100', '23', '3', '0', '64'],
       ['05-01-2018', '133', '100', '4', '2', '0', '64'],
       ['06-01-2018', '153', '300', '0', '8', '0', '64'],
       ['07-01-2018', '500', '200', '0', '5', '500', '64'],
       ['08-01-2018', '2127', '200', '0', '5', '0', '64'],
       ['09-01-2018', '2203', '300', '0', '5', '500', '64']], dtype='<U10')

In [84]:
date , step_count , mood , calories_burned , sleep_hours , activity_status , weight = data.T

In [85]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12-2017',
       '09-12-2017', '10-12-2017', '11-12-2017', '12-12-2017',
       '13-12-2017', '14-12-2017', '15-12-2017', '16-12-2017',
       '17-12-2017', '18-12-2017', '19-12-2017', '20-12-2017',
       '21-12-2017', '22-12-2017', '23-12-2017', '24-12-2017',
       '25-12-2017', '26-12-2017', '27-12-2017', '28-12-2017',
       '29-12-2017', '30-12-2017', '31-12-2017', '01-01-2018',
       '02-01-2018', '03-01-2018', '04-01-2018', '05-01-2018',
       '06-01-2018', '07-01-2018', '08-01-2018', '09-01-2018'],
      dtype='<U10')

In [86]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [87]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [88]:
calories_burned

array(['181', '197', '0', '174', '223', '149', '140', '38', '1', '40',
       '101', '152', '150', '113', '49', '86', '6', '99', '143', '125',
       '129', '6', '9', '10', '72', '150', '141', '156', '57', '72', '17',
       '181', '197', '131', '154', '137', '193', '19', '101', '139',
       '164', '137', '22', '17', '9', '145', '192', '146', '234', '167',
       '16', '17', '32', '35', '220', '116', '23', '44', '131', '86',
       '194', '60', '121', '76', '93', '53', '25', '227', '125', '243',
       '14', '39', '55', '158', '7', '213', '116', '129', '21', '28',
       '16', '180', '138', '176', '99', '5', '1', '10', '47', '84', '23',
       '4', '0', '0', '0', '0'], dtype='<U10')

In [89]:
sleep_hours

array(['5', '8', '5', '4', '5', '6', '6', '7', '5', '6', '8', '5', '6',
       '7', '5', '6', '8', '5', '4', '5', '6', '8', '5', '6', '5', '8',
       '5', '4', '5', '4', '5', '4', '3', '2', '9', '5', '6', '4', '5',
       '8', '4', '5', '6', '5', '6', '5', '6', '5', '6', '5', '6', '7',
       '6', '7', '6', '5', '6', '7', '8', '8', '7', '8', '5', '4', '3',
       '3', '4', '5', '5', '5', '3', '4', '4', '5', '5', '5', '5', '5',
       '5', '4', '3', '4', '5', '5', '4', '5', '3', '3', '3', '2', '3',
       '2', '8', '5', '5', '5'], dtype='<U10')

In [90]:
activity_status

array(['0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '500',
       '500', '500', '500', '500', '500', '500', '500', '500', '0', '0',
       '0', '0', '0', '0', '500', '500', '500', '500', '500', '500',
       '500', '500', '500', '500', '500', '500', '0', '500', '500', '0',
       '500', '500', '500', '500', '500', '0', '500', '500', '500', '500',
       '0', '0', '0', '0', '500', '500', '500', '500', '0', '0', '0', '0',
       '0', '0', '0', '0', '500', '0', '500'], dtype='<U10')

In [91]:
weight

array(['66', '66', '66', '66', '66', '66', '66', '66', '66', '65', '65',
       '65', '65', '65', '65', '65', '65', '65', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64', '64', '64', '64',
       '64', '64', '64', '64', '64', '64', '64', '64'], dtype='<U10')

# change the data type of each column.

In [92]:
data[0]

array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

In [94]:
step_count = np.array(step_count , dtype = "int")

In [95]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [97]:
step_count.dtype

dtype('int32')

In [98]:
calories_burned = np.array(calories_burned , dtype = "int")

In [99]:
calories_burned

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [100]:
calories_burned.dtype

dtype('int32')

In [103]:
sleep_hours = np.array(sleep_hours , dtype = "int")

In [104]:
sleep_hours

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

In [105]:
sleep_hours.dtype

dtype('int32')

In [108]:
weight = np.array(weight , dtype = "int")

In [109]:
weight

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [110]:
weight.dtype

dtype('int32')

# Note - The column mood id filled with categorical data (or) discrete variables.

In [111]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', '300', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', '300', '200', '300', '300',
       '300', '300', '300', '300', '300', '200', '300', '300', '300',
       '300', '300', '300', '300', '300', '300', '300', '200', '300',
       '300', '300', '300', '300', '300', '300', '300', '300', '200',
       '100', '300', '300', '300', '300', '300', '300', '300', '100',
       '200', '200', '100', '100', '200', '200', '300', '200', '200',
       '100', '200', '100', '200', '200', '100', '100', '100', '100',
       '300', '200', '300', '200', '100', '100', '100', '200', '200',
       '100', '100', '300', '200', '200', '300'], dtype='<U10')

In [112]:
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

# Now in the mood column replace 300 ---> happy , 200 ---> neutral , ---> sad. as asked.

In [125]:
mood[mood == "300"] = "Happy"

In [126]:
mood

array(['200', '100', '100', '100', '200', '100', '100', '100', '100',
       '100', '100', '100', 'Happy', '100', '100', '100', '100', '200',
       '200', '200', '200', '200', '200', 'Happy', '200', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', '200',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', '200', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', '200', '100',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       '100', '200', '200', '100', '100', '200', '200', 'Happy', '200',
       '200', '100', '200', '100', '200', '200', '100', '100', '100',
       '100', 'Happy', '200', 'Happy', '200', '100', '100', '100', '200',
       '200', '100', '100', 'Happy', '200', '200', 'Happy'], dtype='<U10')

In [129]:
mood[mood == "200"] = "Neutral"

In [130]:
mood

array(['Neutral', '100', '100', '100', 'Neutral', '100', '100', '100',
       '100', '100', '100', '100', 'Happy', '100', '100', '100', '100',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', '100', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', '100', 'Neutral', 'Neutral',
       '100', '100', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       '100', 'Neutral', '100', 'Neutral', 'Neutral', '100', '100', '100',
       '100', 'Happy', 'Neutral', 'Happy', 'Neutral', '100', '100', '100',
       'Neutral', 'Neutral', '100', '100', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [133]:
mood[mood == "100"] = "Sad"

In [134]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [135]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', '0', '66'],
       ['07-10-2017', '6041', 'Sad', '197', '8', '0', '66'],
       ['08-10-2017', '25', 'Sad', '0', '5', '0', '66'],
       ['09-10-2017', '5461', 'Sad', '174', '4', '0', '66'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', '500', '66'],
       ['11-10-2017', '4545', 'Sad', '149', '6', '0', '66'],
       ['12-10-2017', '4340', 'Sad', '140', '6', '0', '66'],
       ['13-10-2017', '1230', 'Sad', '38', '7', '0', '66'],
       ['14-10-2017', '61', 'Sad', '1', '5', '0', '66'],
       ['15-10-2017', '1258', 'Sad', '40', '6', '0', '65'],
       ['16-10-2017', '3148', 'Sad', '101', '8', '0', '65'],
       ['17-10-2017', '4687', 'Sad', '152', '5', '0', '65'],
       ['18-10-2017', '4732', 'Happy', '150', '6', '500', '65'],
       ['19-10-2017', '3519', 'Sad', '113', '7', '0', '65'],
       ['20-10-2017', '1580', 'Sad', '49', '5', '0', '65'],
       ['21-10-2017', '2822', 'Sad', '86', '6', '0', '65'],
       ['22-10-2017', '181', 'Sad', '6', '8', '0', '65'],
       ['23-10-2017', '3158', 'Neutral', '99', '5', '0', '65'],
       ['24-10-2017', '4383', 'Neutral', '143', '4', '0', '64'],
       ['25-10-2017', '3881', 'Neutral', '125', '5', '0', '64'],
       ['26-10-2017', '4037', 'Neutral', '129', '6', '0', '64'],
       ['27-10-2017', '202', 'Neutral', '6', '8', '0', '64'],
       ['28-10-2017', '292', 'Neutral', '9', '5', '0', '64'],
       ['29-10-2017', '330', 'Happy', '10', '6', '0', '64'],
       ['30-10-2017', '2209', 'Neutral', '72', '5', '0', '64'],
       ['31-10-2017', '4550', 'Happy', '150', '8', '500', '64'],
       ['01-11-2017', '4435', 'Happy', '141', '5', '0', '64'],
       ['02-11-2017', '4779', 'Happy', '156', '4', '0', '64'],
       ['03-11-2017', '1831', 'Happy', '57', '5', '0', '64'],
       ['04-11-2017', '2255', 'Happy', '72', '4', '0', '64'],
       ['05-11-2017', '539', 'Happy', '17', '5', '500', '64'],
       ['06-11-2017', '5464', 'Happy', '181', '4', '0', '64'],
       ['07-11-2017', '6041', 'Neutral', '197', '3', '0', '64'],
       ['08-11-2017', '4068', 'Happy', '131', '2', '0', '64'],
       ['09-11-2017', '4683', 'Happy', '154', '9', '0', '64'],
       ['10-11-2017', '4033', 'Happy', '137', '5', '0', '64'],
       ['11-11-2017', '6314', 'Happy', '193', '6', '500', '64'],
       ['12-11-2017', '614', 'Happy', '19', '4', '500', '64'],
       ['13-11-2017', '3149', 'Happy', '101', '5', '500', '64'],
       ['14-11-2017', '4005', 'Happy', '139', '8', '500', '64'],
       ['15-11-2017', '4880', 'Happy', '164', '4', '500', '64'],
       ['16-11-2017', '4136', 'Happy', '137', '5', '500', '64'],
       ['17-11-2017', '705', 'Happy', '22', '6', '500', '64'],
       ['18-11-2017', '570', 'Neutral', '17', '5', '500', '64'],
       ['19-11-2017', '269', 'Happy', '9', '6', '500', '64'],
       ['20-11-2017', '4275', 'Happy', '145', '5', '0', '64'],
       ['21-11-2017', '5999', 'Happy', '192', '6', '0', '64'],
       ['22-11-2017', '4421', 'Happy', '146', '5', '0', '64'],
       ['23-11-2017', '6930', 'Happy', '234', '6', '0', '64'],
       ['24-11-2017', '5195', 'Happy', '167', '5', '0', '64'],
       ['25-11-2017', '546', 'Happy', '16', '6', '0', '64'],
       ['26-11-2017', '493', 'Happy', '17', '7', '500', '64'],
       ['27-11-2017', '995', 'Happy', '32', '6', '500', '64'],
       ['28-11-2017', '1163', 'Neutral', '35', '7', '500', '64'],
       ['29-11-2017', '6676', 'Sad', '220', '6', '500', '64'],
       ['30-11-2017', '3608', 'Happy', '116', '5', '500', '64'],
       ['01-12-2017', '774', 'Happy', '23', '6', '500', '64'],
       ['02-12-2017', '1421', 'Happy', '44', '7', '500', '64'],
       ['03-12-2017', '4064', 'Happy', '131', '8', '500', '64'],
       ['04-12-2017', '2725', 'Happy', '86', '8', '500', '64'],
       ['05-12-2017', '5934', 'Happy', '194', '7', '500', '64'],
       ['06-12-2017', '1867', 'Happy', '60', '8', '500', '64'],
       ['07-12-2017', '3721', 'Sad', '121', '5', '500', '64'],
       ['08-12-2017', '2374', 'Neutral', '76', '4', '0', '64'],
       ['09-12-2017', '2909', 'Neutral', '93', '3', '500', '64'],
       ['10-12-2017', '1648', 'Sad', '53', '3', '500', '64'],
       ['11-12-2017', '799', 'Sad', '25', '4', '0', '64'],
       ['12-12-2017', '7102', 'Neutral', '227', '5', '500', '64'],
       ['13-12-2017', '3941', 'Neutral', '125', '5', '500', '64'],
       ['14-12-2017', '7422', 'Happy', '243', '5', '500', '64'],
       ['15-12-2017', '437', 'Neutral', '14', '3', '500', '64'],
       ['16-12-2017', '1231', 'Neutral', '39', '4', '500', '64'],
       ['17-12-2017', '1696', 'Sad', '55', '4', '0', '64'],
       ['18-12-2017', '4921', 'Neutral', '158', '5', '500', '64'],
       ['19-12-2017', '221', 'Sad', '7', '5', '500', '64'],
       ['20-12-2017', '6500', 'Neutral', '213', '5', '500', '64'],
       ['21-12-2017', '3575', 'Neutral', '116', '5', '500', '64'],
       ['22-12-2017', '4061', 'Sad', '129', '5', '0', '64'],
       ['23-12-2017', '651', 'Sad', '21', '5', '0', '64'],
       ['24-12-2017', '753', 'Sad', '28', '4', '0', '64'],
       ['25-12-2017', '518', 'Sad', '16', '3', '0', '64'],
       ['26-12-2017', '5537', 'Happy', '180', '4', '500', '64'],
       ['27-12-2017', '4108', 'Neutral', '138', '5', '500', '64'],
       ['28-12-2017', '5376', 'Happy', '176', '5', '500', '64'],
       ['29-12-2017', '3066', 'Neutral', '99', '4', '500', '64'],
       ['30-12-2017', '177', 'Sad', '5', '5', '0', '64'],
       ['31-12-2017', '36', 'Sad', '1', '3', '0', '64'],
       ['01-01-2018', '299', 'Sad', '10', '3', '0', '64'],
       ['02-01-2018', '1447', 'Neutral', '47', '3', '0', '64'],
       ['03-01-2018', '2599', 'Neutral', '84', '2', '0', '64'],
       ['04-01-2018', '702', 'Sad', '23', '3', '0', '64'],
       ['05-01-2018', '133', 'Sad', '4', '2', '0', '64'],
       ['06-01-2018', '153', 'Happy', '0', '8', '0', '64'],
       ['07-01-2018', '500', 'Neutral', '0', '5', '500', '64'],
       ['08-01-2018', '2127', 'Neutral', '0', '5', '0', '64'],
       ['09-01-2018', '2203', 'Happy', '0', '5', '500', '64']],
      dtype='<U10')

In [136]:
activity_status

array(['0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '500', '0', '0', '0', '0', '500', '0', '0', '0', '0', '0', '500',
       '500', '500', '500', '500', '500', '500', '500', '500', '0', '0',
       '0', '0', '0', '0', '500', '500', '500', '500', '500', '500',
       '500', '500', '500', '500', '500', '500', '0', '500', '500', '0',
       '500', '500', '500', '500', '500', '0', '500', '500', '500', '500',
       '0', '0', '0', '0', '500', '500', '500', '500', '0', '0', '0', '0',
       '0', '0', '0', '0', '500', '0', '500'], dtype='<U10')

# Like above also change the categorical data of activity_status.

In [147]:
np.unique(activity_status)

array(['Active', 'Not active'], dtype='<U10')

In [148]:
activity_status[activity_status == "0"] = "Not active"

In [149]:
activity_status

array(['Not active', 'Not active', 'Not active', 'Not active', 'Active',
       'Not active', 'Not active', 'Not active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Not active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Not active', 'Not active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Not active', 'Active',
       'Active', 'Not active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Not active', 'Active', 'Active', 'Active', 'Active',
       'Not active', 'Not active', 'Not active', 'Not active', 'Active',
       'Active', 'Active', 'Active', 'Not active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Not active',
       'Not active', 'Not active', 'Active', 'Not active', 'Active'],
      dtype='<U10')

In [150]:
activity_status[activity_status == "500"] = "Active"

In [151]:
activity_status

array(['Not active', 'Not active', 'Not active', 'Not active', 'Active',
       'Not active', 'Not active', 'Not active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Not active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Not active', 'Not active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Not active', 'Active',
       'Active', 'Not active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Not active', 'Active', 'Active', 'Active', 'Active',
       'Not active', 'Not active', 'Not active', 'Not active', 'Active',
       'Active', 'Active', 'Active', 'Not active', 'Not active',
       'Not active', 'Not active', 'Not active', 'Not active',
       'Not active', 'Not active', 'Active', 'Not active', 'Active'],
      dtype='<U10')

In [152]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Not active', '66'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Not active', '66'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Not active', '66'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Not active', '66'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active', '66'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Not active', '66'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Not active', '66'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Not active', '66'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Not active', '66'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Not active', '65'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Not active', '65'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Not active', '65'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active', '65'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Not active', '65'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Not active', '65'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Not active', '65'],
       ['22-10-2017', '181', 'Sad', '6', '8', 'Not active', '65'],
       ['23-10-2017', '3158', 'Neutral', '99', '5', 'Not active', '65'],
       ['24-10-2017', '4383', 'Neutral', '143', '4', 'Not active', '64'],
       ['25-10-2017', '3881', 'Neutral', '125', '5', 'Not active', '64'],
       ['26-10-2017', '4037', 'Neutral', '129', '6', 'Not active', '64'],
       ['27-10-2017', '202', 'Neutral', '6', '8', 'Not active', '64'],
       ['28-10-2017', '292', 'Neutral', '9', '5', 'Not active', '64'],
       ['29-10-2017', '330', 'Happy', '10', '6', 'Not active', '64'],
       ['30-10-2017', '2209', 'Neutral', '72', '5', 'Not active', '64'],
       ['31-10-2017', '4550', 'Happy', '150', '8', 'Active', '64'],
       ['01-11-2017', '4435', 'Happy', '141', '5', 'Not active', '64'],
       ['02-11-2017', '4779', 'Happy', '156', '4', 'Not active', '64'],
       ['03-11-2017', '1831', 'Happy', '57', '5', 'Not active', '64'],
       ['04-11-2017', '2255', 'Happy', '72', '4', 'Not active', '64'],
       ['05-11-2017', '539', 'Happy', '17', '5', 'Active', '64'],
       ['06-11-2017', '5464', 'Happy', '181', '4', 'Not active', '64'],
       ['07-11-2017', '6041', 'Neutral', '197', '3', 'Not active', '64'],
       ['08-11-2017', '4068', 'Happy', '131', '2', 'Not active', '64'],
       ['09-11-2017', '4683', 'Happy', '154', '9', 'Not active', '64'],
       ['10-11-2017', '4033', 'Happy', '137', '5', 'Not active', '64'],
       ['11-11-2017', '6314', 'Happy', '193', '6', 'Active', '64'],
       ['12-11-2017', '614', 'Happy', '19', '4', 'Active', '64'],
       ['13-11-2017', '3149', 'Happy', '101', '5', 'Active', '64'],
       ['14-11-2017', '4005', 'Happy', '139', '8', 'Active', '64'],
       ['15-11-2017', '4880', 'Happy', '164', '4', 'Active', '64'],
       ['16-11-2017', '4136', 'Happy', '137', '5', 'Active', '64'],
       ['17-11-2017', '705', 'Happy', '22', '6', 'Active', '64'],
       ['18-11-2017', '570', 'Neutral', '17', '5', 'Active', '64'],
       ['19-11-2017', '269', 'Happy', '9', '6', 'Active', '64'],
       ['20-11-2017', '4275', 'Happy', '145', '5', 'Not active', '64'],
       ['21-11-2017', '5999', 'Happy', '192', '6', 'Not active', '64'],
       ['22-11-2017', '4421', 'Happy', '146', '5', 'Not active', '64'],
       ['23-11-2017', '6930', 'Happy', '234', '6', 'Not active', '64'],
       ['24-11-2017', '5195', 'Happy', '167', '5', 'Not active', '64'],
       ['25-11-2017', '546', 'Happy', '16', '6', 'Not active', '64'],
       ['26-11-2017', '493', 'Happy', '17', '7', 'Active', '64'],
       ['27-11-2017', '995', 'Happy', '32', '6', 'Active', '64'],
       ['28-11-2017', '1163', 'Neutral', '35', '7', 'Active', '64'],
       ['29-11-2017', '6676', 'Sad', '220', '6', 'Active', '64'],
       ['30-11-2017', '3608', 'Happy', '116', '5', 'Active', '64'],
       ['01-12-2017', '774', 'Happy', '23', '6', 'Active', '64'],
       ['02-12-2017', '1421', 'Happy', '44', '7', 'Active', '64'],
       ['03-12-2017', '4064', 'Happy', '131', '8', 'Active', '64'],
       ['04-12-2017', '2725', 'Happy', '86', '8', 'Active', '64'],
       ['05-12-2017', '5934', 'Happy', '194', '7', 'Active', '64'],
       ['06-12-2017', '1867', 'Happy', '60', '8', 'Active', '64'],
       ['07-12-2017', '3721', 'Sad', '121', '5', 'Active', '64'],
       ['08-12-2017', '2374', 'Neutral', '76', '4', 'Not active', '64'],
       ['09-12-2017', '2909', 'Neutral', '93', '3', 'Active', '64'],
       ['10-12-2017', '1648', 'Sad', '53', '3', 'Active', '64'],
       ['11-12-2017', '799', 'Sad', '25', '4', 'Not active', '64'],
       ['12-12-2017', '7102', 'Neutral', '227', '5', 'Active', '64'],
       ['13-12-2017', '3941', 'Neutral', '125', '5', 'Active', '64'],
       ['14-12-2017', '7422', 'Happy', '243', '5', 'Active', '64'],
       ['15-12-2017', '437', 'Neutral', '14', '3', 'Active', '64'],
       ['16-12-2017', '1231', 'Neutral', '39', '4', 'Active', '64'],
       ['17-12-2017', '1696', 'Sad', '55', '4', 'Not active', '64'],
       ['18-12-2017', '4921', 'Neutral', '158', '5', 'Active', '64'],
       ['19-12-2017', '221', 'Sad', '7', '5', 'Active', '64'],
       ['20-12-2017', '6500', 'Neutral', '213', '5', 'Active', '64'],
       ['21-12-2017', '3575', 'Neutral', '116', '5', 'Active', '64'],
       ['22-12-2017', '4061', 'Sad', '129', '5', 'Not active', '64'],
       ['23-12-2017', '651', 'Sad', '21', '5', 'Not active', '64'],
       ['24-12-2017', '753', 'Sad', '28', '4', 'Not active', '64'],
       ['25-12-2017', '518', 'Sad', '16', '3', 'Not active', '64'],
       ['26-12-2017', '5537', 'Happy', '180', '4', 'Active', '64'],
       ['27-12-2017', '4108', 'Neutral', '138', '5', 'Active', '64'],
       ['28-12-2017', '5376', 'Happy', '176', '5', 'Active', '64'],
       ['29-12-2017', '3066', 'Neutral', '99', '4', 'Active', '64'],
       ['30-12-2017', '177', 'Sad', '5', '5', 'Not active', '64'],
       ['31-12-2017', '36', 'Sad', '1', '3', 'Not active', '64'],
       ['01-01-2018', '299', 'Sad', '10', '3', 'Not active', '64'],
       ['02-01-2018', '1447', 'Neutral', '47', '3', 'Not active', '64'],
       ['03-01-2018', '2599', 'Neutral', '84', '2', 'Not active', '64'],
       ['04-01-2018', '702', 'Sad', '23', '3', 'Not active', '64'],
       ['05-01-2018', '133', 'Sad', '4', '2', 'Not active', '64'],
       ['06-01-2018', '153', 'Happy', '0', '8', 'Not active', '64'],
       ['07-01-2018', '500', 'Neutral', '0', '5', 'Active', '64'],
       ['08-01-2018', '2127', 'Neutral', '0', '5', 'Not active', '64'],
       ['09-01-2018', '2203', 'Happy', '0', '5', 'Active', '64']],
      dtype='<U10')

# Data Analysis.

# Calculate the average step count of the data.

In [154]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Not active', '66'],
      dtype='<U10')

In [157]:
step_count.mean()

2935.9375

# On which date the step count was the highest.

In [159]:
step_count.max()

7422

In [160]:
step_count.min()

25

In [161]:
np.max(step_count)

7422

In [162]:
np.sort(step_count)

array([  25,   36,   61,  133,  153,  177,  181,  202,  221,  269,  292,
        299,  330,  437,  493,  500,  518,  539,  546,  570,  614,  651,
        702,  705,  753,  774,  799,  995, 1163, 1230, 1231, 1258, 1421,
       1447, 1580, 1648, 1696, 1831, 1867, 2127, 2203, 2209, 2255, 2374,
       2599, 2725, 2822, 2909, 3066, 3148, 3149, 3158, 3519, 3575, 3608,
       3721, 3881, 3941, 4005, 4033, 4037, 4061, 4064, 4068, 4108, 4136,
       4275, 4340, 4383, 4421, 4435, 4545, 4550, 4683, 4687, 4732, 4779,
       4880, 4921, 5195, 5376, 5461, 5464, 5464, 5537, 5934, 5999, 6041,
       6041, 6314, 6500, 6676, 6915, 6930, 7102, 7422])

In [164]:
np.argsort(step_count)

array([ 2, 86,  8, 91, 92, 85, 16, 21, 74, 44, 22, 87, 23, 70, 51, 93, 80,
       30, 50, 43, 37, 78, 90, 42, 79, 56, 66, 52, 53,  7, 71,  9, 57, 88,
       14, 65, 72, 28, 61, 94, 95, 24, 29, 63, 89, 59, 15, 64, 84, 10, 38,
       17, 13, 76, 55, 62, 19, 68, 39, 35, 20, 77, 58, 33, 82, 41, 45,  6,
       18, 47, 26,  5, 25, 34, 11, 12, 27, 40, 73, 49, 83,  3, 31,  0, 81,
       60, 46,  1, 32, 36, 75, 54,  4, 48, 67, 69], dtype=int64)

In [165]:
np.argsort(step_count)[-1]

69

In [166]:
date[np.argsort(step_count)[-1]]

'14-12-2017'

In [169]:
data[:,:2]

array([['06-10-2017', '5464'],
       ['07-10-2017', '6041'],
       ['08-10-2017', '25'],
       ['09-10-2017', '5461'],
       ['10-10-2017', '6915'],
       ['11-10-2017', '4545'],
       ['12-10-2017', '4340'],
       ['13-10-2017', '1230'],
       ['14-10-2017', '61'],
       ['15-10-2017', '1258'],
       ['16-10-2017', '3148'],
       ['17-10-2017', '4687'],
       ['18-10-2017', '4732'],
       ['19-10-2017', '3519'],
       ['20-10-2017', '1580'],
       ['21-10-2017', '2822'],
       ['22-10-2017', '181'],
       ['23-10-2017', '3158'],
       ['24-10-2017', '4383'],
       ['25-10-2017', '3881'],
       ['26-10-2017', '4037'],
       ['27-10-2017', '202'],
       ['28-10-2017', '292'],
       ['29-10-2017', '330'],
       ['30-10-2017', '2209'],
       ['31-10-2017', '4550'],
       ['01-11-2017', '4435'],
       ['02-11-2017', '4779'],
       ['03-11-2017', '1831'],
       ['04-11-2017', '2255'],
       ['05-11-2017', '539'],
       ['06-11-2017', '5464'],
       ['07-11-2017', '6041'],
       ['08-11-2017', '4068'],
       ['09-11-2017', '4683'],
       ['10-11-2017', '4033'],
       ['11-11-2017', '6314'],
       ['12-11-2017', '614'],
       ['13-11-2017', '3149'],
       ['14-11-2017', '4005'],
       ['15-11-2017', '4880'],
       ['16-11-2017', '4136'],
       ['17-11-2017', '705'],
       ['18-11-2017', '570'],
       ['19-11-2017', '269'],
       ['20-11-2017', '4275'],
       ['21-11-2017', '5999'],
       ['22-11-2017', '4421'],
       ['23-11-2017', '6930'],
       ['24-11-2017', '5195'],
       ['25-11-2017', '546'],
       ['26-11-2017', '493'],
       ['27-11-2017', '995'],
       ['28-11-2017', '1163'],
       ['29-11-2017', '6676'],
       ['30-11-2017', '3608'],
       ['01-12-2017', '774'],
       ['02-12-2017', '1421'],
       ['03-12-2017', '4064'],
       ['04-12-2017', '2725'],
       ['05-12-2017', '5934'],
       ['06-12-2017', '1867'],
       ['07-12-2017', '3721'],
       ['08-12-2017', '2374'],
       ['09-12-2017', '2909'],
       ['10-12-2017', '1648'],
       ['11-12-2017', '799'],
       ['12-12-2017', '7102'],
       ['13-12-2017', '3941'],
       ['14-12-2017', '7422'],
       ['15-12-2017', '437'],
       ['16-12-2017', '1231'],
       ['17-12-2017', '1696'],
       ['18-12-2017', '4921'],
       ['19-12-2017', '221'],
       ['20-12-2017', '6500'],
       ['21-12-2017', '3575'],
       ['22-12-2017', '4061'],
       ['23-12-2017', '651'],
       ['24-12-2017', '753'],
       ['25-12-2017', '518'],
       ['26-12-2017', '5537'],
       ['27-12-2017', '4108'],
       ['28-12-2017', '5376'],
       ['29-12-2017', '3066'],
       ['30-12-2017', '177'],
       ['31-12-2017', '36'],
       ['01-01-2018', '299'],
       ['02-01-2018', '1447'],
       ['03-01-2018', '2599'],
       ['04-01-2018', '702'],
       ['05-01-2018', '133'],
       ['06-01-2018', '153'],
       ['07-01-2018', '500'],
       ['08-01-2018', '2127'],
       ['09-01-2018', '2203']], dtype='<U10')

In [170]:
# On which date was there was teh minimum number of step_count.

In [171]:
data[:,:2]

array([['06-10-2017', '5464'],
       ['07-10-2017', '6041'],
       ['08-10-2017', '25'],
       ['09-10-2017', '5461'],
       ['10-10-2017', '6915'],
       ['11-10-2017', '4545'],
       ['12-10-2017', '4340'],
       ['13-10-2017', '1230'],
       ['14-10-2017', '61'],
       ['15-10-2017', '1258'],
       ['16-10-2017', '3148'],
       ['17-10-2017', '4687'],
       ['18-10-2017', '4732'],
       ['19-10-2017', '3519'],
       ['20-10-2017', '1580'],
       ['21-10-2017', '2822'],
       ['22-10-2017', '181'],
       ['23-10-2017', '3158'],
       ['24-10-2017', '4383'],
       ['25-10-2017', '3881'],
       ['26-10-2017', '4037'],
       ['27-10-2017', '202'],
       ['28-10-2017', '292'],
       ['29-10-2017', '330'],
       ['30-10-2017', '2209'],
       ['31-10-2017', '4550'],
       ['01-11-2017', '4435'],
       ['02-11-2017', '4779'],
       ['03-11-2017', '1831'],
       ['04-11-2017', '2255'],
       ['05-11-2017', '539'],
       ['06-11-2017', '5464'],
       ['07-11-2017', '6041'],
       ['08-11-2017', '4068'],
       ['09-11-2017', '4683'],
       ['10-11-2017', '4033'],
       ['11-11-2017', '6314'],
       ['12-11-2017', '614'],
       ['13-11-2017', '3149'],
       ['14-11-2017', '4005'],
       ['15-11-2017', '4880'],
       ['16-11-2017', '4136'],
       ['17-11-2017', '705'],
       ['18-11-2017', '570'],
       ['19-11-2017', '269'],
       ['20-11-2017', '4275'],
       ['21-11-2017', '5999'],
       ['22-11-2017', '4421'],
       ['23-11-2017', '6930'],
       ['24-11-2017', '5195'],
       ['25-11-2017', '546'],
       ['26-11-2017', '493'],
       ['27-11-2017', '995'],
       ['28-11-2017', '1163'],
       ['29-11-2017', '6676'],
       ['30-11-2017', '3608'],
       ['01-12-2017', '774'],
       ['02-12-2017', '1421'],
       ['03-12-2017', '4064'],
       ['04-12-2017', '2725'],
       ['05-12-2017', '5934'],
       ['06-12-2017', '1867'],
       ['07-12-2017', '3721'],
       ['08-12-2017', '2374'],
       ['09-12-2017', '2909'],
       ['10-12-2017', '1648'],
       ['11-12-2017', '799'],
       ['12-12-2017', '7102'],
       ['13-12-2017', '3941'],
       ['14-12-2017', '7422'],
       ['15-12-2017', '437'],
       ['16-12-2017', '1231'],
       ['17-12-2017', '1696'],
       ['18-12-2017', '4921'],
       ['19-12-2017', '221'],
       ['20-12-2017', '6500'],
       ['21-12-2017', '3575'],
       ['22-12-2017', '4061'],
       ['23-12-2017', '651'],
       ['24-12-2017', '753'],
       ['25-12-2017', '518'],
       ['26-12-2017', '5537'],
       ['27-12-2017', '4108'],
       ['28-12-2017', '5376'],
       ['29-12-2017', '3066'],
       ['30-12-2017', '177'],
       ['31-12-2017', '36'],
       ['01-01-2018', '299'],
       ['02-01-2018', '1447'],
       ['03-01-2018', '2599'],
       ['04-01-2018', '702'],
       ['05-01-2018', '133'],
       ['06-01-2018', '153'],
       ['07-01-2018', '500'],
       ['08-01-2018', '2127'],
       ['09-01-2018', '2203']], dtype='<U10')

In [172]:
np.min(step_count)

25

In [174]:
np.sort(step_count)

array([  25,   36,   61,  133,  153,  177,  181,  202,  221,  269,  292,
        299,  330,  437,  493,  500,  518,  539,  546,  570,  614,  651,
        702,  705,  753,  774,  799,  995, 1163, 1230, 1231, 1258, 1421,
       1447, 1580, 1648, 1696, 1831, 1867, 2127, 2203, 2209, 2255, 2374,
       2599, 2725, 2822, 2909, 3066, 3148, 3149, 3158, 3519, 3575, 3608,
       3721, 3881, 3941, 4005, 4033, 4037, 4061, 4064, 4068, 4108, 4136,
       4275, 4340, 4383, 4421, 4435, 4545, 4550, 4683, 4687, 4732, 4779,
       4880, 4921, 5195, 5376, 5461, 5464, 5464, 5537, 5934, 5999, 6041,
       6041, 6314, 6500, 6676, 6915, 6930, 7102, 7422])

In [183]:
np.argsort(step_count)

array([ 2, 86,  8, 91, 92, 85, 16, 21, 74, 44, 22, 87, 23, 70, 51, 93, 80,
       30, 50, 43, 37, 78, 90, 42, 79, 56, 66, 52, 53,  7, 71,  9, 57, 88,
       14, 65, 72, 28, 61, 94, 95, 24, 29, 63, 89, 59, 15, 64, 84, 10, 38,
       17, 13, 76, 55, 62, 19, 68, 39, 35, 20, 77, 58, 33, 82, 41, 45,  6,
       18, 47, 26,  5, 25, 34, 11, 12, 27, 40, 73, 49, 83,  3, 31,  0, 81,
       60, 46,  1, 32, 36, 75, 54,  4, 48, 67, 69], dtype=int64)

In [188]:
date[np.argsort(step_count)[0]]

'08-10-2017'

# So the step_count is lowest on the above date with number of steps of "25".

In [190]:
# Other way to solve the above questions

In [192]:
np.argmax(step_count)

'14-12-2017'

In [193]:
date[np.argmax(step_count)]

'14-12-2017'

In [194]:
np.argmin(step_count)

2

In [195]:
date[np.argmin(step_count)]

'08-10-2017'

#  What is the most frequent "mood for the given data.

In [198]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [196]:
np.sum(mood == "Happy")

40

In [199]:
np.sum(mood == "Sad")

29

In [200]:
np.sum(mood == "Neutral")

27

# so the most frequently the user is happy 40 times.

In [202]:
np.unique(mood, return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([40, 27, 29], dtype=int64))

# Can be done in the above way too.

# See if the "mood" is influencing the step_count.

In [213]:
step_count[mood == "Sad"].mean()

2103.0689655172414

In [214]:
step_count[mood == "Neutral"].mean()

3153.777777777778

In [215]:
step_count[mood == "Happy"].mean()

3392.725

# Note - So form the above we acn say that the user have high step count when he is happy.

# See if activity_status is affecting the step_count.

In [221]:
step_count[activity_status == "Active"].mean()

3226.5714285714284

In [220]:
step_count[activity_status == "Not active"].mean()

2709.8888888888887

# Note - From the above we can clearly say that the user took more steps when is active.